layout_spectrum: 1
typography_spectrum: 0.08767522
color:
  saturation: 0.5148936
  brandStrength: 0.8468085
  lightness: 0.6021277
  brandColors:
    - '#FFFFFF'
    - '#597CA4'
    - '#D3DCE7'
    - '#859FBC'
  rhythmicContrast: 0.3234043
name: Giantshopper
